database:
  host: localhost
  port: 3306
  name: minecraft
  user: root
  password: password

availablePronouns:
  he/him: "&3(&bHe&3/&bHim&3)&r"
  she/her: "&3(&dShe&3/&dHer&3)&r"
  they/them: "&5(&aThey&5/&aThem&5)&r"
  it/its: "&8(&7It&8/&7Its&8)&r"
  he/they: "&2(&aHe&2/&aThey&2)&r"
  she/they: "&4(&cShe&4/&cThey&4)&r"
  xe/xem: "&8(&7Xe&8/&7Xem&8)&r"
  ze/zir: "&8(&7Ze&8/&7Zir&8)&r"
