database:
  host: localhost
  port: 3306
  name: minecraft
  user: root
  password: password

availablePronouns:
  he/him: "&bHe&3/&bHim&r"
  she/her: "&dShe&5/&dHer&r"
  they/them: "&eThey&6/&eThem&r"
  xe/xem: "&bXe&3/&bXem&r"
  ze/zir: "&eZe&3/&eZir&r"
