name: PronounsMC
version: ${version}
main: com.alfie51m.pronounsMC.PronounsMC
api-version: 1.21
softdepend: [PlaceholderAPI]
commands:
  pronouns:
    description: Main command for pronouns
    usage: /pronouns <command>

permissions:
  pronouns.get:
    description: Permission to get another player's pronouns.
    default: op
  pronouns.reload:
    description: Permission to reload the plugin config.
    default: op