name: PronounsPlugin
version: 1.0.0
main: com.alfie51m.pronounsPlugin.PronounsPlugin
api-version: 1.21
commands:
  pronouns:
    description: Main command for pronouns
    usage: /pronouns <command>
    aliases: [pronoun]

permissions:
  pronouns.get:
    description: Permission to get another player's pronouns
    default: op
  pronouns.reload:
    description: Permission to reload the plugin config
    default: op